In [220]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Importing Libraries and Loading the Dataset

In [221]:
# Importing all the necessary libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [222]:
#Loading the Heart dataset
heart_df = pd.read_csv("/content/drive/MyDrive/heart.csv")

In [223]:
#Displaying Random 5 samples
heart_df.sample(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
466,55,M,NAP,120,0,0,ST,125,Y,2.5,Flat,1
111,57,M,ASY,150,255,0,Normal,92,Y,3.0,Flat,1
233,41,M,ASY,112,250,0,Normal,142,N,0.0,Up,0
811,58,F,ASY,100,248,0,LVH,122,N,1.0,Flat,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0

In [224]:
#Getting dataset summary
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [225]:
#Getting dataset statistics
heart_df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [226]:
heart_df.describe(include="all")

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

Data Preprocessing

In [227]:
#Checking the Null Values
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [228]:
#Checking the duplicates
heart_df.duplicated().sum()

np.int64(0)

In [229]:
#Checking number of unique value in each feature
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [230]:
heart_df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [231]:
cat_col = heart_df.select_dtypes(include='object').columns

Converting Categorical Variables to Numeric

In [232]:
for col in cat_col:
  print(col)
  print((heart_df[col].unique()),list(range(heart_df[col].nunique())))
  heart_df[col].replace((heart_df[col].unique()),range(heart_df[col].nunique()),inplace=True)
  print('*'*90)
  print()

Sex
['M' 'F'] [0, 1]
******************************************************************************************

ChestPainType
['ATA' 'NAP' 'ASY' 'TA'] [0, 1, 2, 3]
******************************************************************************************

RestingECG
['Normal' 'ST' 'LVH'] [0, 1, 2]
******************************************************************************************

ExerciseAngina
['N' 'Y'] [0, 1]
******************************************************************************************

ST_Slope
['Up' 'Flat' 'Down'] [0, 1, 2]
******************************************************************************************

In [233]:
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,3,110,264,0,0,132,0,1.2,1,1
914,68,0,2,144,193,1,0,141,0,3.4,1,1
915,57,0,2,130,131,0,0,115,1,1.2,1,1
916,57,1,0,130,236,0,2,174,0,0.0,1,1
917,38,0,1,138,175,0,0,173,0,0.0,0,0

In [234]:
heart_df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

Imputing the 0 values in cholesterol column with KNN Imputer

In [235]:
np.nan

nan

In [236]:
heart_df['Cholesterol'].replace(0, np.nan, inplace=True)

In [237]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)

In [238]:
heart_df['Cholesterol'].isna().sum()

np.int64(0)

In [239]:
count = 0
for i in heart_df['Cholesterol']:
  if i == 0:
    count +=1
    print(count)

Doing the same for Resting Blood Pressure

In [240]:
heart_df['RestingBP'][heart_df['RestingBP'] == 0]

449    0.0
Name: RestingBP, dtype: float64

In [241]:
from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0, np.nan, inplace=True)
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)

In [242]:
heart_df['RestingBP'].unique()

array([140., 160., 130., 138., 150., 120., 110., 136., 115., 100., 124.,
       113., 125., 145., 112., 132., 118., 170., 142., 190., 135., 180.,
       108., 155., 128., 106.,  92., 200., 122.,  98., 105., 133.,  95.,
        80., 137., 185., 165., 126., 152., 116., 144., 154., 134., 104.,
       139., 131., 141., 178., 146., 158., 123., 102.,  96., 143., 172.,
       156., 114., 127., 101., 174.,  94., 148., 117., 192., 129., 164.])

In [243]:
heart_df['RestingBP'].isnull() .sum()

np.int64(0)

Change Columns type  to int

In [244]:
withoutOldpeak = heart_df.columns
withoutOldpeak = withoutOldpeak.drop('Oldpeak')
heart_df[withoutOldpeak]=heart_df[withoutOldpeak].astype('int32')

In [245]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

Data Visualization

In [246]:
pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [247]:
heart_df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
206,35,0,0,120,308,0,2,180,0,0.0,0,0

In [248]:
heart_df.corr()['HeartDisease'][:-1].sort_values()

MaxHR            -0.400421
Sex              -0.305445
RestingECG        0.061011
Cholesterol       0.101263
RestingBP         0.118333
FastingBS         0.267291
Age               0.282039
Oldpeak           0.403951
ChestPainType     0.459017
ExerciseAngina    0.494282
ST_Slope          0.558771
Name: HeartDisease, dtype: float64

In [249]:
import plotly.express as px

In [250]:
px.line(heart_df.corr()['HeartDisease'][:-1].sort_values())

Age and HeartDisease Distribution

In [251]:
px.sunburst(heart_df,path=['HeartDisease','Age'])

In [252]:
px.histogram (heart_df,x='Age',color='HeartDisease')

Percentage of Heart Disease Data Distribution

In [253]:
#Percentage of HeartDisease data distribution
px.pie(heart_df,names='HeartDisease',title = 'Percentage of HeartDisease data distribution')

Sex vs Heart Disease

In [254]:
px.histogram(heart_df,x='Sex',color='HeartDisease')

ChestPain Type vs HeartDisease

In [276]:
px.histogram(heart_df,x='ChestPainType',color='HeartDisease')
#ChestPainType : ATA = 0, NAP = 1, ASY = 2, TA = 3

RestingBP vs HeartDisease

In [256]:
heart_df['RestingBP'].unique()

array([140, 160, 130, 138, 150, 120, 110, 136, 115, 100, 124, 113, 125,
       145, 112, 132, 118, 170, 142, 190, 135, 180, 108, 155, 128, 106,
        92, 200, 122,  98, 105, 133,  95,  80, 137, 185, 165, 126, 152,
       116, 144, 154, 134, 104, 139, 131, 141, 178, 146, 158, 123, 102,
        96, 143, 172, 156, 114, 127, 101, 174,  94, 148, 117, 192, 129,
       164], dtype=int32)

In [257]:
px.sunburst(heart_df,path=['HeartDisease','RestingBP'])

FastingBS vs Heart Disease

In [258]:
px.histogram(heart_df,x='FastingBS', color='HeartDisease')

MaxHR vs Heart Disease

In [259]:
px.sunburst(heart_df,path=['HeartDisease','MaxHR'])

In [260]:
px.violin(heart_df,x='HeartDisease',y='MaxHR', color = 'HeartDisease')

Oldpeak vs Heart Disease

In [261]:
px.violin(heart_df,x='HeartDisease',y='Oldpeak', color = 'HeartDisease')

ST_Slope vs Heart Disease

In [262]:
px.histogram(heart_df,x='ST_Slope',color='HeartDisease')

ExcersiseAngina vs Heart Disease

In [263]:
px.histogram(heart_df, x='ExerciseAngina', color='HeartDisease')

Train Test Split

In [264]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    heart_df.drop('HeartDisease', axis=1),
    heart_df['HeartDisease'],
    test_size=0.2,
    random_state=42,
    stratify=heart_df['HeartDisease']
)

Logistic Regression

In [265]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
best_solver = ''
test_score = np.zeros(6)
for i,n in enumerate(solver):
  lr = LogisticRegression(solver=n).fit(X_train, y_train)
  test_score[i] = lr.score (X_test, y_test)
  if lr.score(X_test, y_test) == test_score.max():
    best_solver = n

  lr = LogisticRegression(solver=best_solver)
  lr.fit(X_train, y_train)
  y_pred = lr.predict(X_test)
  print(f'LogisticRegression Score: {accuracy_score(y_test, y_pred)}')

LogisticRegression Score: 0.8532608695652174
LogisticRegression Score: 0.8586956521739131
LogisticRegression Score: 0.8586956521739131
LogisticRegression Score: 0.8586956521739131
LogisticRegression Score: 0.8586956521739131
LogisticRegression Score: 0.8586956521739131

In [266]:
import pickle
file = open('LogisticR.pk1', 'wb')
pickle.dump(lr, file)

Support Vector Machine (SVM)

In [267]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score
kernels = {'linear':0, 'poly':0, 'sigmoid':0}
best = ''
for i in kernels:
  svm = SVC(kernel=i)
  svm.fit(X_train, y_train)
  yhat = svm.predict(X_test)
  kernels[i] = f1_score(y_test, yhat,  average = "weighted")
  if kernels[i] == max(kernels.values()):
    best = i
svm = SVC(kernel=best)
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
print(f'SVM f1_score kernel({best}): {f1_score(y_test, svm_pred, average="weighted")}')

SVM f1_score kernel(linear): 0.8422922535440344

In [268]:
import pickle
file = open('SVM.pk1', 'wb')
pickle.dump(svm, file)

Decision Tree Classifier

In [269]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(class_weight='balanced')
param_grid = {
    'max_depth': [3, 4, 5, 6, 7, 8],
    'min_samples_split': [2, 3, 4],
    'min_samples_leaf': [1, 2, 3, 4],
    'random_state': [0, 42]
}
grid_search = GridSearchCV(dtree, param_grid, cv=5)
grid_search.fit(X_train, y_train)
Ctree = DecisionTreeClassifier(**grid_search.best_params_, class_weight='balanced')
Ctree.fit(X_train, y_train)
dtc_pred = Ctree.predict(X_test)
print("DecisionTree's Accuracy: ", accuracy_score(y_test, dtc_pred))

DecisionTree's Accuracy:  0.8097826086956522

In [270]:
import pickle
file = open('Ctree.pk1', 'wb')
pickle.dump(Ctree, file)

Random Forest Classifier

In [271]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier()
param_grid = {
    'n_estimators': [50, 100, 150, 500],
    'max_depth': ['sqrt','log2',None],
    'max_depth':[3, 6, 9, 19],
    'max_leaf_nodes': [3, 6, 9],
}
grid_search = GridSearchCV(rfc, param_grid)
grid_search.fit(X_train, y_train)
rfctree = RandomForestClassifier(**grid_search.best_params_)
rfctree.fit(X_train, y_train)
rfc_pred = rfctree.predict(X_test)
print("RandomForest'sClassifier Accuracy: ", accuracy_score(y_test, rfc_pred))

RandomForest'sClassifier Accuracy:  0.8532608695652174

In [272]:
import pickle
file = open('rfc.pk1', 'wb')
pickle.dump(rfc, file)

In [273]:
import pickle
from google.colab import files

# Save models
pickle.dump(rfc, open('rfc.pkl', 'wb'))
pickle.dump(Ctree, open('Ctree.pkl', 'wb'))
pickle.dump(svm, open('SVM.pkl', 'wb'))
pickle.dump(lr, open('LogisticR.pkl', 'wb'))
pickle.dump(lr, open('grid.pkl', 'wb'))

# Download all files
files.download('rfc.pkl')
files.download('Ctree.pkl')
files.download('SVM.pkl')
files.download('LogisticR.pkl')
files.download('grid.pkl')

Grid Search

In [274]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier()

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10]
}

grid = GridSearchCV(rf, param_grid, cv=3)
grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 10], 'n_estimators': [100, 200]})

In [275]:
import pickle
file = open('grid.pk1', 'wb')
pickle.dump(grid, file)